name: merge dependabot upgrades

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'mutation tests'
jobs:
  merge-me:
    name: merge dependabot upgrades
    runs-on: ubuntu-latest
    steps:
      - name: merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: MERGE